#!/usr/bin/env zsh

# Make vim the default editor.
export EDITOR='vim';

# Disable auto update for Homebrew.
export HOMEBREW_NO_AUTO_UPDATE = 1;

# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8';
export LC_ALL='en_US.UTF-8';

# Highlight section titles in manual pages.
export LESS_TERMCAP_md="${yellow}";

# Don’t clear the screen after quitting a manual page.
export MANPAGER='less -X';

# Replace dircolors (GNU specific)
export CLICOLOR=YES

# Avoid issues with `gpg` as installed via Homebrew.
# https://stackoverflow.com/a/42265848/96656
export GPG_TTY=$(tty);